inputs:
  npm-token:
    required: true

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./.node-version

    - run: corepack enable
      shell: bash

    - name: Can publish
      run: npx can-npm-publish --verbose
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm-token }}
      shell: bash
