runs:
  using: composite
  steps:
    - name: Run prepare
      run: yarn prepare

    - name: Build
      run: yarn build

    - name: Publish
      run: yarn npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
