inputs:
  npm-token:
    required: true
  working-directory:
    required: true

runs:
  using: composite
  steps:
    - name: Run prepare
      run: yarn prepare
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - run: corepack enable
      shell: bash

    - name: Build
      run: yarn build
      working-directory: ${{ inputs.working-directory }}
      shell: bash

    - name: Publish
      run: yarn npm publish
      working-directory: ${{ inputs.working-directory }}
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm-token }}
      shell: bash
