name: eslint-plugin-js@CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop
      - feature/**
      - main
    paths:
      - '.node-version'
      - 'config/**'
      - 'modules/shared-for-eslint-plugin/**'
      - 'packages/eslint-plugin-js/**'
      - 'prettier.config.js'
      - 'yarn.lock'

jobs:
  check-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    defaults:
      run:
        working-directory: ./packages/eslint-plugin-js
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: corepack enable

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run prepare
        run: yarn prepare

      - name: Run lint
        run: yarn lint

      - name: Run spell-check
        run: yarn spell-check

      - name: Run type-check
        run: yarn type-check

      - name: Run test
        run: yarn test
