name: eslint-config-js@CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - develop
      - feature/**
      - main
    paths:
      - '.node-version'
      - 'config/**'
      - 'dry-run/dr-eslint-config-sc-js/**'
      - 'modules/shared-for-eslint-config/**'
      - 'packages/eslint-config-js/**'
      - 'prettier.config.js'
      - 'yarn.lock'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/common-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run lint
        run: yarn lint

  spell-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/common-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run spell-check
        run: yarn spell-check

  type-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-config-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/common-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run type-check
        run: yarn type-check

  dry-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    defaults:
      run:
        working-directory: ./packages/eslint-config-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/ci-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run dry run
        run: yarn dry-run
