name: eslint-plugin-js@CD

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'eslint-plugin-sc-js/v*'

jobs:
  check-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-plugin-js
    steps:
      - uses: actions/checkout@v4

      - name: check publish
        uses: ./.github/actions/check-publish

  pre-check-lint:
    needs: [check-publish]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-plugin-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/common-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run lint
        run: yarn lint

  pre-check-spell-check:
    needs: [check-publish]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-plugin-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/common-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run spell-check
        run: yarn spell-check

  pre-check-type-check:
    needs: [check-publish]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-plugin-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/common-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run type-check
        run: yarn type-check

  pre-check-dry-run:
    needs: [check-publish]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    defaults:
      run:
        working-directory: ./packages/eslint-plugin-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/ci-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run dry run
        run: yarn dry-run

  pre-check-test:
    needs: [check-publish]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]
    defaults:
      run:
        working-directory: ./packages/eslint-plugin-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/ci-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run test
        run: yarn test

  publish:
    needs: [check-publish, pre-check-lint, pre-check-spell-check, pre-check-type-check, pre-check-dry-run, pre-check-test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/eslint-plugin-js
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/common-setup

      - name: publish
        uses: ./.github/actions/publish
