name: local-eslint-plugin-js@CI

permissions:
  contents: read

on:
  pull_request:
    branches:
      - local/**
    paths:
      - '.node-version'
      - 'config/**'
      - 'dry-run/dr-eslint-plugin-sc-js/**'
      - 'modules/shared-for-eslint-plugin/**'
      - 'packages/eslint-plugin-js/**'
      - 'prettier.config.js'
      - 'yarn.lock'

env:
  WORKING_DIRECTORY: ./packages/eslint-plugin-js

defaults:
  run:
    working-directory: ${{ env.WORKING_DIRECTORY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/actions/common-setup

      - name: Run prepare
        run: yarn prepare

      - name: Run lint
        run: yarn lint

      - name: Run spell-check
        run: yarn spell-check

      - name: Run type-check
        run: yarn type-check

      - name: Run test
        run: yarn test
